import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  passwordPromptOverlay: {
    position: 'absolute',
    top: 0,
    shadowRadius: 10,
    elevation: 4,
  },
  passwordPromptTitle: {
    fontSize: 19,
    fontWeight: 'bold',
    color: '#c62828',
    marginBottom: 8,
    textAlign: 'center',
  },
  passwordPromptText: {
    fontSize: 15,
    color: '#333',
    marginBottom: 14,
    textAlign: 'center',
  },
  container: {
    marginTop: 32,
    marginBottom: 32,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 4,
  },
  profileCard: {
    backgroundColor: '#fff',
    borderRadius: 24,
    padding: 24,
    maxWidth: 420,
    width: '90%',
    alignItems: 'center',
    alignSelf: 'center',
    marginTop: 32,
    marginBottom: 32,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 4,
  },
  passwordPromptBox: {
    backgroundColor: '#fff',
    borderRadius: 18,
    padding: 28,
    marginHorizontal: 24,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.12,
    shadowRadius: 8,
    elevation: 6,
    minWidth: 260,
    maxWidth: 340,
  },
  topBar: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
    marginBottom: 4,
    minHeight: 32,
  },
  logoutButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 4,
    paddingHorizontal: 10,
    marginRight: 2,
    backgroundColor: 'rgba(200,40,40,0.08)',
    borderRadius: 16,
    alignSelf: 'flex-end',
    marginTop: 8,
    marginBottom: 8,
  },
  logoutButtonText: {
    color: '#c62828',
    fontWeight: 'bold',
    fontSize: 16,
    marginLeft: 6,
    letterSpacing: 0.2,
  },
  headerCentered: {
    alignItems: 'center',
    marginBottom: 12,
  },
  titleRowCentered: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 2,
    marginTop: 8,
  },
  card: {
    borderRadius: 18,
    paddingVertical: 24,
    paddingHorizontal: 28,
    marginHorizontal: 8,
    marginBottom: 24,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.07,
    shadowRadius: 8,
    elevation: 2,
  },
  deleteButton: {
    backgroundColor: '#c62828',
    borderRadius: 18,
    paddingVertical: 14,
    paddingHorizontal: 24,
    marginTop: 12,
    marginBottom: 24,
    alignSelf: 'center',
    minWidth: 220,
    alignItems: 'center',
    shadowColor: '#c62828',
    shadowOpacity: 0.10,
    shadowRadius: 6,
    elevation: 2,
  },
  deleteButtonText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 18,
    textAlign: 'center',
    letterSpacing: 0.2,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 18,
    marginTop: 8,
    justifyContent: 'center',
  },
  avatarBox: {
    width: 86,
    height: 86,
    borderRadius: 43,
    backgroundColor: '#e3f2fd',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 18,
    borderWidth: 2,
    borderColor: '#90caf9',
    shadowColor: '#90caf9',
    shadowOpacity: 0.12,
    shadowRadius: 6,
    elevation: 2,
  },
  avatar: {
    width: 76,
    height: 76,
    borderRadius: 38,
    resizeMode: 'cover',
  },
  avatarPlaceholder: {
    width: 76,
    height: 76,
    borderRadius: 38,
    backgroundColor: '#bbdefb',
    justifyContent: 'center',
    alignItems: 'center',
  },
  avatarInitial: {
    fontSize: 32,
    color: '#1976d2',
    fontWeight: 'bold',
  },
  headerInfoCentered: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  titleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 2,
  },
  title: {
    fontSize: 22,
    color: '#333',
    fontWeight: 'bold',
    marginRight: 6,
  },
  editIcon: {
    marginLeft: 2,
    padding: 2,
  },
  email: {
    color: '#1976d2',
    fontSize: 15,
    marginBottom: 2,
    fontWeight: '600',
    textAlign: 'center',
    marginTop: 10,
  },
  infoBlock: {
    alignItems: 'center',
    marginTop: 8,
  },
  label: {
    fontWeight: 'bold',
    alignSelf: 'center',
    marginTop: 12,
    marginBottom: 2,
    color: '#2e7d32',
  },
  value: {
    alignSelf: 'center',
    fontSize: 16,
    color: '#333',
    marginBottom: 4,
  },
  input: {
    width: 260,
    backgroundColor: '#f8f8f8', 
    borderRadius: 8,
    padding: 10,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: '#ccc',
    fontSize: 16,
    alignSelf: 'center',
  },
  saveButton: {
    backgroundColor: '#2e7d32',
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 18,
    marginRight: 8,
    minWidth: 90,
    alignItems: 'center',
  },
  saveButtonText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 16,
    textAlign: 'center',
  },
  cancelButton: {
    backgroundColor: '#eee',
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 18,
    minWidth: 90,
    alignItems: 'center',
  },
  cancelButtonText: {
    color: '#2e7d32',
    fontWeight: 'bold',
    fontSize: 16,
    textAlign: 'center',
  },
  row: {
    flexDirection: 'row',
    marginTop: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  infoHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    marginBottom: 0,
  },
  avatarPickerButton: {
    backgroundColor: '#e3f2fd',
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 16,
    marginRight: 8,
    marginTop: 8,
  },
  avatarPickerText: {
    color: '#1976d2',
    fontWeight: 'bold',
    fontSize: 15,
  },

});

export default styles;
