export const mapFilterModalStyles = StyleSheet.create({
  modalContainer: {
    flex: 1,
    backgroundColor: colors.overlay,
    justifyContent: 'center',
    alignItems: 'center',
  },
  card: {
    width: '90%',
    backgroundColor: colors.white,
    borderRadius: 16,
    padding: 24,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  title: {
    color: colors.primary,
    marginBottom: spacing.md,
    alignSelf: 'center',
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: spacing.md,
  },
  label: {
    fontSize: 15,
    color: colors.darkGray,
    marginRight: 8,
    minWidth: 90,
  },
  textInput: {
    flex: 1,
    fontSize: 15,
    color: colors.black,
    backgroundColor: colors.lightGray,
    borderRadius: 8,
    paddingHorizontal: spacing.xs,
    height: 38,
  },
  picker: {
    backgroundColor: colors.lightGray,
    borderRadius: 8,
  },
  button: {
    backgroundColor: colors.primary,
    borderRadius: 8,
    paddingHorizontal: 18,
    paddingVertical: 10,
    marginHorizontal: 4,
  },
  buttonText: {
    color: colors.white,
    fontWeight: 'bold',
    fontSize: 16,
  },
});
import { StyleSheet } from 'react-native';
import { colors, spacing } from './index';

export const mapSearchBarStyles = StyleSheet.create({
  container: {
    position: 'absolute',
    top: 28,
    left: 0,
    right: 0,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.md,
    paddingVertical: 0,
    backgroundColor: 'transparent',
    zIndex: 10,
    elevation: 10,
  },
  inputWrapper: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.white,
    borderRadius: 16,
    paddingHorizontal: spacing.md,
    height: 44,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.10,
    shadowRadius: 8,
    elevation: 6,
  },
  textInput: {
    flex: 1,
    fontSize: 16,
    color: colors.black,
    backgroundColor: 'transparent',
    borderRadius: 8,
    paddingHorizontal: 0,
    height: 44,
  },
  filterButton: {
    marginLeft: spacing.sm,
    backgroundColor: colors.primary,
    borderRadius: 16,
    padding: 10,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.10,
    shadowRadius: 8,
    elevation: 6,
  },
  listButton: {
    marginLeft: spacing.sm,
    backgroundColor: colors.error,
    borderRadius: 16,
    padding: 10,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.10,
    shadowRadius: 8,
    elevation: 6,
  },
  mapButton: {
    marginLeft: spacing.sm,
    backgroundColor: colors.primary,
    borderRadius: 16,
    padding: 10,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.10,
    shadowRadius: 8,
    elevation: 6,
  },
});
